
service: myserverlessproject
# app and org for use with dashboard.serverless.com
app: my-sources
org: mysources

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  environment:
    usersTable: ${self:custom.usersTable}
    foldersTable: ${self:custom.foldersTable}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

custom:
  usersTable: users
  foldersTable: folders

functions:
  getUser:
    handler: lambdas/endpoints/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true 

  listAllUserFolders:
    handler: lambdas/endpoints/listAllUserFolders.handler
    events:
      - http:
          path: list-user-folders/{ID}
          method: GET
          cors: true

  getFolderKeys:
    handler: lambdas/endpoints/getFolderKeys.handler
    events:
      - http:
          path: get-folder-keys/{ID}
          method: GET
          cors: true

  listCategoryFolders:
    handler: lambdas/endpoints/listCategoryFolders.handler
    events:
      - http:
          path: list-category-folders/{ID}
          method: POST
          cors: true

  getCategoryKeys:
    handler: lambdas/endpoints/getCategoryKeys.handler
    events:
      - http:
          path: get-category-keys/{ID}
          method: POST
          cors: true
    
  moveItem:
    handler: lambdas/endpoints/moveItem.handler
    events:
      - http:
          path: move-item/{ID}
          method: POST
          cors: true

  addFile:
    handler: lambdas/endpoints/addFile.handler
    events:
      - http:
          path: add-file/{ID}
          method: POST
          cors: true

  deleteFolder:
    handler: lambdas/endpoints/deleteFolder.handler
    events:
      - http:
          path: delete-folder/{ID}
          method: POST
          cors: true

  createUser:
    handler: lambdas/endpoints/createUser.handler
    events:
      - http:
          path: create-user/{ID}
          method: POST
          cors: true

  createFolder:
    handler: lambdas/endpoints/createFolder.handler
    events:
      - http:
          path: create-folder/{ID}
          method: POST
          cors: true
          
  updateFolder:
    handler: lambdas/endpoints/updateFolder.handler
    events:
      - http:
          path: update-folder/{ID}
          method: POST
          cors: true 

  removeFile:
    handler: lambdas/endpoints/removeFileKey.handler
    events:
      - http:
          path: remove-file/{KEY}
          method: POST
          cors: true

resources:
  Resources:
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTable}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        
    FoldersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.foldersTable}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: id_cat
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

        GlobalSecondaryIndexes:
          - IndexName: id_cat
            KeySchema:
              - AttributeName: id_cat
                KeyType: HASH
            Projection:
              ProjectionType: ALL
              